# Generated by Django 4.2.1 on 2023-05-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_delete_genre_delete_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
