# Generated by Django 4.2.1 on 2023-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_alter_author_date_of_birth_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
