# Generated by Django 4.2.1 on 2023-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
